# This is a basic workflow to help you get started with Actions

name: Clone workflow

on: 
  workflow_dispatch:
jobs:
  job_one:
    name: clone
    runs-on: Ubuntu-latest
    steps:
      - name: testing
        uses: appleboy/ssh-action@main
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            git clone git@github.com:michaelko92/michaelko92.github.io.git
          

